version: '3'
services:
  web:
    image: ${ECR_REPOSITORY}:web
    depends_on:
      - mysql
    build:
      context: php-apache
      args:
        TIMEZONE: ${TIMEZONE}
        ENVIRONMENT: ${ENVIRONMENT}
        SERVER_NAME: ${SERVER_NAME}
        SERVER_ALIAS: ${SERVER_ALIAS}
    ports:
      - ${PUBLIC_IPV4}:${APACHE_PORT}:80
      - ${PUBLIC_IPV4}:${APACHE_PORT_SSL}:443
    links:
      - mysql
    volumes:
      - ./app:/var/www/html
      - ./php-apache/cert:/etc/apache2/ssl/
  mysql:
    image: ${ECR_REPOSITORY}:mysql
    build:
      context: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./.data/db:/var/lib/mysql"
    ports:
      - ${MYSQL_PORT}:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    volumes:
      - ../.data/phpmyadmin/sessions:/sessions
