version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.2.11
  build:
    commands:
    - php --version
  post_build:
    commands:
    - php --version
artifacts:
  files:
    -  README.md